### PR TITLE
Rule: Remove Hashtags + Improved titlecase

### PR DESCRIPTION
**Pull request by chrisgrieser**
issue #37 & added some stuff to the titlecase rule while I was here

### CODE REVIEW

**Comment by platers** [comment]
Could you rename the rule and description to `Format YAML tags` or something that makes it clear its formatting tags?

**Comment by chrisgrieser** [comment]
Okay, have done so.

**Comment by platers** [comment]
thanks, just a small thing, YAML-Header can just be YAML, for naming consistency with other rules. And description uses YAML frontmatter.

**Comment by chrisgrieser** [comment]
sure, done 👍

**Comment by platers** [comment]
oh, run `npm run compile` and `npm run lint` to update the documentation/readme and lint.

**Comment by chrisgrieser** [comment]
Sorry, I know some JavaScript, but this my first time with TypeScript and `npm`. I think I got it, I ran both commands, I hope everything works fine now?

**Comment by platers** [comment]
No problem! The PR looks good, except now somehow main.js got committed. Its in the .gitignore, so not sure how that happened. Can you remove main.js?

**Comment by chrisgrieser** [comment]
probably because I manually uploaded files to my fork. Haven't really had the time / incentive to learn using `git`, as all my repos are mostly small solo-projects. 😅
(Guess I will look into it at some point.)

**Pull request merged**
