### PR TITLE
Add unit test to ensure all properties can be initialized

### LINKED ISSUE #374: Add an unit test to ensure that all option class properties have corresponding option control
Inspired by #369

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #374

### CODE REVIEW

**Comment by pjkaufman** [comment]
I have not forgotten about this, but I do see there is reflection involved which is typically something I avoid like the plague.

**Comment by mnaoumov** [comment]
@pjkaufman I can rewrite without reflection if that's your only concern :)

**Comment by mnaoumov** [comment]
@pjkaufman ready

**Comment by pjkaufman** [comment]
It looks good from what I have seen so far. I will take a closer look at the no settings logic and make sure I follow. Once that is done, if I see no issues, I will merge this in. Thanks for the help @mnaoumov !

**Comment by mnaoumov** [comment]
@pjkaufman in short, the logic is the following: all properties from corresponding `Options` classes should have matching settings UI control, unless we explicitly marked that property with `@RuleBuilder.noSettingControl()`

**Comment by pjkaufman** [comment]
Yeah. That is the gist of what I am seeing. But I want to make sure I understand the code before approving. It will likely be in the next day or 2 when I finish my review based on my freetime.

**Review by pjkaufman — APPROVED** [review]
Looks good to me. I will merge it on in. Thanks @mnaoumov  for adding this!

**Pull request merged**
