### PR TITLE
Add british spelling for realise.

### PR DESCRIPTION
**Pull request by BradleyYeo**
How can I configure obsidian-linter to convert american spelling to british?

### CODE REVIEW

**Comment by pjkaufman** [comment]
Hey @BradleyYeo , I am not sure the Linter is supposed to auto-correct for specofic dialects of English. You may just want to add that as a custom replacement value since `realize` is a valid word.

**Comment by BradleyYeo** [comment]
Hi Peter,

Do you have suggestions for how I can do that?

Thank you,

Bradley

**Comment by pjkaufman** [comment]
This is a little convoluted, but it is the only way the Linter currently allows for the functionality you are referring to:
You go to the custom tab in the Linter settings and have to add 2 rules per word you want to replace (one capitalized and one uncapitalized). So for what you are trying to do with realize you would add two rules to the custom replacement that would look something like the following:
image

**Comment by pjkaufman** [comment]
There does seem to be a desire to extend the auto-correct list with custom values, but so far I am not sure as to the best way to go about it so I have left it alone. However I may go ahead and add something for it at some point. I just have a lot of things that have been requested and a lot of functionality to keep functional.

**Comment by BradleyYeo** [comment]
It works thank you!

Thank you,

Bradley

**Comment by pjkaufman** [comment]
I am going to go ahead and close this @BradleyYeo . Hopefully the example provided is enough to tackle your needs at this time.

**Pull request closed without merging**
