### PR TITLE
update Chinese translate

### PR DESCRIPTION
**Pull request by Ooopz**
A better translate than Google, fix some error and enhance text consistency.

### CODE REVIEW

**Comment by Ooopz** [comment]
I have test the translate, and it looks good. By the way I think menu structure need an update.

**Comment by pjkaufman** [comment]
> I have test the translate, and it looks good. By the way I think menu structure need an update.

Could you elaborate on what you mean by a menu update being needed?

**Comment by Ooopz** [comment]
In content setting, the rules may need reordered.
better order as below:
Auto-correct Common Misspellings,
Blockquote Style,
Emphasis Style,
Strong Style,
Quote Style,
Ordered List Style,
Unordered List Style,
Convert Bullet List Markers,
Remove Consecutive List Markers,
Remove Empty List Markers,
Remove Hyphenated Line Breaks,
No Bare URLs, 
Proper Ellipsis

Remove Multiple Spaces and Two Spaces Between Lines with Content can move to spacing setting

**Comment by pjkaufman** [comment]
> In content setting, the rules may need reordered. better order as below: Auto-correct Common Misspellings, Blockquote Style, Emphasis Style, Strong Style, Quote Style, Ordered List Style, Unordered List Style, Convert Bullet List Markers, Remove Consecutive List Markers, Remove Empty List Markers, Remove Hyphenated Line Breaks, No Bare URLs, Proper Ellipsis
> 
> Remove Multiple Spaces and Two Spaces Between Lines with Content can move to spacing setting

Generally speaking the order is alphabetical. However I do agree with the comments about the spacing values.

**Comment by Ooopz** [comment]
I haven't notice alphabetical order because I'm using Chinese setting... XD

**Comment by pjkaufman** [comment]
> I haven't notice alphabetical order because I'm using Chinese setting... XD

Gotcha. It may not be visible in other languages.

**Comment by Ooopz** [comment]
conflict has been solved, it's ready for merge.

**Comment by pjkaufman** [comment]
I will take a look. It looks like there are a decent bit of changes, so I need to see about comparing what the meanings are before and after. I don't know Chinese, so the best I can do for validation is check with Google Translate to see how it turns out.

**Review by pjkaufman — CHANGES_REQUESTED** [review]
Thanks for putting in the work to help better the Chinese translation!

I notice a couple of things that will need to be addressed before the changes can be merged:
- The use of YAML has been changed to Yaml. This is fine if that is how it is referred to in Chinese. Otherwise the plugin will use "YAML".
- There are references to Latex, but the math block identifier is not a Latex parser, so I am not sure where Latex is coming from
- Tables are only recognized if they follow the guidelines set forth by github (Obsidian may allow other table types, but the Linter can only recognize github's tables)
- At least 1 blank line was added
- Why are the warning levels converted to all capitalized English values instead of using the Chinese words for those log levels?

**Review by pjkaufman — CHANGES_REQUESTED** [review]
Thanks for putting in the work to help better the Chinese translation!

Most of the comments relate to the spelling of YAML so do not be worried. There are just about a dozen that are not.

I notice a couple of things that will need to be addressed before the changes can be merged:
- The use of YAML has been changed to Yaml. This is fine if that is how it is referred to in Chinese. Otherwise the plugin will use "YAML".
- There are references to Latex, but the math block identifier is not a Latex parser, so I am not sure where Latex is coming from
- Tables are only recognized if they follow the guidelines set forth by github (Obsidian may allow other table types, but the Linter can only recognize github's tables)
- At least 1 blank line was added
- Why are the warning levels converted to all capitalized English values instead of using the Chinese words for those log levels?

**Comment by Ooopz** [comment]
Thanks for detailed review, some explain below:

1. I change YAML to Yaml just because it's a common usage of my company, both YAML or Yaml are fine. I can replace all Yaml to YAML insted.
2. Math block is highly related to Latxe, in Chinese Internet environment there is no different between math block and Latex block, this translate will be more clear to Chinese users.
3. Table is the same reason as Latex, github is redundant.
4. There are two blank lines, it should be my carelessness.
5. Warning levels do not need translate as I  do not translate `tags` and `aliases`, people use this features definitely konws the meaning. Another reason is we don't use Chinese tranlation to specialized term as debug level, user will feel weared when it be translated.

At final, I will replace all Yaml to YAML, and delete all blank lines. Latex and table condition will leave as it is.

Maybe a new pull request is easier to handle?

**Pull request closed without merging**
