### PR TITLE
Dedupe YAML Arrays

### LINKED ISSUE #857: FR: Delete Duplicate Array Values from YAML
Further to our discussion at #855, please add a toggle or perhaps preferably a rule (without a setting) that removes any duplicate keys, e.g. from alias property (actually any number over one instance should be removed).  

Of course, diactric characters like `ä`, etc. are not to be taken as equals of `a`, etc. And "Lion" does not equal "lion".  But these are of course self-explanatory.

Thank you,

Best

### PR DESCRIPTION
**Pull request by pjkaufman**
Fixes #857 
Relates to #954 
Relates to #508 

Adds the ability to remove duplicate values from a YAML array.

Changes Made:
- Add a new rule for removing duplicate YAML array values
- Tries to abide by the current YAML format as much as possible
- Adds options to enable duplicate removal for tags, aliases, normal arrays, and an option to list out keys of YAML arrays to ignore

### CODE REVIEW

**Comment by grantx2016** [comment]
I just tested this with the latest release of Linter and it's not working for me. Similarly the sorting not working either. I can confirm that I have enabled these options in the plugin settings. By comparison, if I manually select the relevant lines in the YAML block and run the command 'sort u' then it dedupes and sorts correctly.

**Comment by pjkaufman** [comment]
I just pushed a patch. Please check version 1.23.1.

**Comment by Drakemoor** [comment]
It works for me now. Thank you.

**Comment by grantx2016** [comment]
All working A-OK. Thanks for the quick update for this feature. It's a ripper. 👍

**Pull request merged**
